[package]
name = "wf75"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
tera = "1"
actix-web = "4"
actix-files = "*"
env_logger = "*"
lazy_static = "1.4.0"
serde_json = "1.0.111"
toml = "0.8.8"
