spaces = [
    { id = 1, name = "Gang 0.0x", floor = 0 },
    { id = 2, name = "Gang 0.1x", floor = 0 },
    { id = 3, name = "Muondetector", floor = 0 },
    { id = 4, name = "Gang 0.2x", floor = 0 },
    { id = 5, name = "Gang 0.3x", floor = 0 },
    { id = 6, name = "Personeelskamer", floor = 0 },
    { id = 7, name = "Gang 0.5x", floor = 0 },
    { id = 8, name = "Bepstee", floor = -1 },
    { id = 9, name = "Aula", floor = 0 },
    { id = 10, name = "Gang 1.0x", floor = 1 },
    { id = 11, name = "Gang 1.1x", floor = 1 },
    { id = 12, name = "Gang 0.0x", floor = 0 },
    { id = 1, name = "Gang 0.0x", floor = 0 },
    { id = 1, name = "Gang 0.0x", floor = 0 },
    { id = 1, name = "Gang 0.0x", floor = 0 },
    { id = 1, name = "Gang 0.0x", floor = 0 },
    { id = 1, name = "Gang 0.0x", floor = 0 },
    { id = 1, name = "Gang 0.0x", floor = 0 },
    { id = 1, name = "Gang 0.0x", floor = 0 },
    { id = 1, name = "Gang 0.0x", floor = 0 },
    { id = 1, name = "Gang 0.0x", floor = 0 },
    { id = 1, name = "Gang 0.0x", floor = 0 },
    { id = 1, name = "Gang 0.0x", floor = 0 },
    { id = 1, name = "Gang 0.0x", floor = 0 },
    { id = 1, name = "Gang 0.0x", floor = 0 },
    { id = 1, name = "Gang 0.0x", floor = 0 },
]

[[spheres]]
id = "0101"
space = 1
neighbours = [
    { id = "0102", angle = 0 },
]

[[spheres]]
id = "0102"
space = 1
neighbours = [
    { id = "0101", angle = 270 },
    { id = "0103", angle = 100 },
]

[[spheres]]
id = "0103"
space = 1
neighbours = [
    { id = "0102", angle = 200 },
    { id = "0104", angle = 20 },
]

[[spheres]]
id = "0104"
space = 1
neighbours = [
    { id = "0103", angle = 0 },
    { id = "0105", angle = 180 },
]

[[spheres]]
id = "0105"
space = 1
neighbours = [
    { id = "0104", angle = 270 },
    { id = "0106", angle = 90 },
]

[[spheres]]
id = "0106"
space = 1
neighbours = [
    { id = "0105", angle = 90 },
    { id = "0201", angle = 180 },
]

[[spheres]]
id = "0201"
space = 2
neighbours = [
    { id = "0106", angle = 283 },
    { id = "0202", angle = 103 },
]

[[spheres]]
id = "0202"
space = 2
neighbours = [
    { id = "0201", angle = 283 },
    { id = "0202", angle = 103 },
]

[[spheres]]
id = "0203"
space = 2
neighbours = [
    { id = "0201", angle = 283 },
    { id = "0202", angle = 103 },
]

[[spheres]]
id = "0204"
space = 2
neighbours = [
    { id = "0201", angle = 283 },
    { id = "0202", angle = 103 },
]

[[spheres]]
id = "0205"
space = 2
neighbours = [
    { id = "0201", angle = 283 },
    { id = "0202", angle = 103 },
]

[[spheres]]
id = "0206"
space = 2
neighbours = [
    { id = "0201", angle = 283 },
    { id = "0202", angle = 103 },
]

[[spheres]]
id = "0207"
space = 2
neighbours = [
    { id = "0201", angle = 283 },
    { id = "0202", angle = 103 },
]

[[spheres]]
id = "0208"
space = 2
neighbours = [
    { id = "0201", angle = 283 },
    { id = "0202", angle = 103 },
]

[[spheres]]
id = "0209"
space = 2
neighbours = [
    { id = "0201", angle = 283 },
    { id = "0202", angle = 103 },
]

[[spheres]]
id = "0210"
space = 2
neighbours = [
    { id = "0201", angle = 283 },
    { id = "0202", angle = 103 },
]

[[spheres]]
id = "0211"
space = 2
neighbours = [
    { id = "0201", angle = 283 },
    { id = "0202", angle = 103 },
]

[[spheres]]
id = "0212"
space = 2
neighbours = [
    { id = "0201", angle = 283 },
    { id = "0202", angle = 103 },
]

[[spheres]]
id = "0213"
space = 2
neighbours = [
    { id = "0201", angle = 283 },
    { id = "0202", angle = 103 },
]

[[spheres]]
id = "0214"
space = 2
neighbours = [
    { id = "0201", angle = 283 },
    { id = "0202", angle = 103 },
]

[[spheres]]
id = "0215"
space = 2
neighbours = [
    { id = "0201", angle = 283 },
    { id = "0202", angle = 103 },
]

[[spheres]]
id = "0216"
space = 2
neighbours = [
    { id = "0201", angle = 283 },
    { id = "0202", angle = 103 },
]

[[spheres]]
id = "1419"
space = -1
neighbours = [
    { id = "1420", angle = -1 },
    { id = "1412", angle = -1 },
]

[[spheres]]
id = "1420"
space = -1
neighbours = [
    { id = "1419", angle = -1 },
    { id = "1421", angle = -1 },
]

[[spheres]]
id = "1421"
space = -1
neighbours = [
    { id = "1420", angle = -1 },
    { id = "1424", angle = -1 },
    { id = "1422", angle = -1 },
]

[[spheres]]
id = "1424"
space = -1
neighbours = [
    { id = "1421", angle = -1 },
]

[[spheres]]
id = "1422"
space = -1
neighbours = [
    { id = "1421", angle = -1 },
    { id = "1423", angle = -1 },
]

[[spheres]]
id = "1423"
space = -1
neighbours = [
    { id = "1422", angle = -1 },
]

[[spheres]]
id = "1907"
space = -1
neighbours = [
    { id = "1903", angle = -1 },
]

[[spheres]]
id = "1903"
space = -1
neighbours = [
    { id = "1907", angle = -1 },
    { id = "1904", angle = -1 },
    { id = "1902", angle = -1 },
]

[[spheres]]
id = "1904"
space = -1
neighbours = [
    { id = "1903", angle = -1 },
    { id = "1905", angle = -1 },
]

[[spheres]]
id = "1905"
space = -1
neighbours = [
    { id = "1904", angle = -1 },
    { id = "1906", angle = -1 },
]

[[spheres]]
id = "1906"
space = -1
neighbours = [
    { id = "1905", angle = -1 },
]

[[spheres]]
id = "1902"
space = -1
neighbours = [
    { id = "1903", angle = -1 },
    { id = "1901", angle = -1 },
]

[[spheres]]
id = "1901"
space = -1
neighbours = [
    { id = "1902", angle = -1 },
]

[[spheres]]
id = "1412"
space = -1
neighbours = [
    { id = "1419", angle = -1 },
]

[[spheres]]
id = "1007"
space = -1
neighbours = [
    { id = "1805", angle = -1 },
]

[[spheres]]
id = "1805"
space = -1
neighbours = [
    { id = "1007", angle = -1 },
    { id = "1804", angle = -1 },
]

[[spheres]]
id = "1804"
space = -1
neighbours = [
    { id = "1805", angle = -1 },
    { id = "1803", angle = -1 },
]

[[spheres]]
id = "1803"
space = -1
neighbours = [
    { id = "1804", angle = -1 },
    { id = "1802", angle = -1 },
]

[[spheres]]
id = "1802"
space = -1
neighbours = [
    { id = "1803", angle = -1 },
    { id = "1801", angle = -1 },
]

[[spheres]]
id = "1801"
space = -1
neighbours = [
    { id = "1802", angle = -1 },
]
