spaces = [
    { id = 1, name = "Gang 0.0x", floor = 0 },
    { id = 2, name = "Gang 0.1x", floor = 0 },
    { id = 3, name = "Muondetector", floor = 0 },
    { id = 4, name = "Gang 0.2x", floor = 0 },
    { id = 5, name = "Gang 0.3x", floor = 0 },
    { id = 6, name = "Personeelskamer", floor = 0 },
    { id = 7, name = "Gang 0.5x", floor = 0 },
    { id = 8, name = "Bepstee", floor = -1 },
    { id = 9, name = "Aula", floor = 0 },
    { id = 10, name = "Gang 1.0x", floor = 1 },
    { id = 11, name = "Gang 1.1x", floor = 1 },
    { id = 12, name = "Gang 0.0x", floor = 0 },
    { id = 1, name = "Gang 0.0x", floor = 0 },
    { id = 1, name = "Gang 0.0x", floor = 0 },
    { id = 1, name = "Gang 0.0x", floor = 0 },
    { id = 1, name = "Gang 0.0x", floor = 0 },
    { id = 1, name = "Gang 0.0x", floor = 0 },
    { id = 1, name = "Gang 0.0x", floor = 0 },
    { id = 1, name = "Gang 0.0x", floor = 0 },
    { id = 1, name = "Gang 0.0x", floor = 0 },
    { id = 1, name = "Gang 0.0x", floor = 0 },
    { id = 1, name = "Gang 0.0x", floor = 0 },
    { id = 1, name = "Gang 0.0x", floor = 0 },
    { id = 1, name = "Gang 0.0x", floor = 0 },
    { id = 1, name = "Gang 0.0x", floor = 0 },
    { id = 1, name = "Gang 0.0x", floor = 0 },
]

[[spheres]]
id = "0101"
space = 1
neighbours = [
    { id = "0102", angle = 0 },
]


[[spheres]]
id = "0102"
space = 1
neighbours = [
    { id = "0101", angle = 270 },
    { id = "0103", angle = 100 },
]


[[spheres]]
id = "0103"
space = 1
neighbours = [
    { id = "0102", angle = 200 },
    { id = "0104", angle = 20 },
]


[[spheres]]
id = "0104"
space = 1
neighbours = [
    { id = "0103", angle = 0 },
    { id = "0105", angle = 180 },
]


[[spheres]]
id = "0105"
space = 1
neighbours = [
    { id = "0104", angle = 270 },
    { id = "0106", angle = 90 },
]


[[spheres]]
id = "0106"
space = 1
neighbours = [
    { id = "0105", angle = 90 },
    { id = "0201", angle = 180 },
]


[[spheres]]
id = "0201"
space = 2
neighbours = [
    {id="0106", angle=283},
    {id="0202", angle=103},
    {id="0203", angle=90}
]


[[spheres]]
id = "0202"
space = 2
neighbours = [
    {id="0201", angle=283},
    {id="0204", angle=103}
]


[[spheres]]
id = "0203"
space = 2
neighbours = [
    {id="0201", angle=283},
    {id="0204", angle=103},
    {id="0205", angle=90}
]


[[spheres]]
id = "0204"
space = 2
neighbours = [
    {id="0202", angle=283},
    {id="0203", angle=103},
    {id="0205", angle=90},
    {id="1008", angle=90}
]


[[spheres]]
id = "0205"
space = 2
neighbours = [
    {id="0203", angle=283},
    {id="0204", angle=103},
    {id="0206", angle=90},
    {id="0211", angle=90}
]


[[spheres]]
id = "0206"
space = 2
neighbours = [
    {id="0205", angle=283},
    {id="0207", angle=103},
    {id="0211", angle=90}
]


[[spheres]]
id = "0207"
space = 2
neighbours = [
    {id="0206", angle=283},
    {id="0208", angle=103},
    {id="0212", angle=90}
]


[[spheres]]
id = "0208"
space = 2
neighbours = [
    {id="0207", angle=283},
    {id="0212", angle=103},
    {id="0213", angle=90},
    {id="0214", angle=90}
]


[[spheres]]
id = "0209"
space = 2
neighbours = [
    {id="0210", angle=283},
    {id="2302", angle=103}
]


[[spheres]]
id = "0210"
space = 2
neighbours = [
    {id="0209", angle=283},
    {id="0211", angle=103}
]


[[spheres]]
id = "0211"
space = 2
neighbours = [
    {id="0205", angle=283},
    {id="0206", angle=103}
]


[[spheres]]
id = "0212"
space = 2
neighbours = [
    {id="0207", angle=283},
    {id="0208", angle=103},
    {id="2305", angle=90}
]


[[spheres]]
id = "0213"
space = 2
neighbours = [
    {id="0208", angle=283},
    {id="2305", angle=103}
]


[[spheres]]
id = "0214"
space = 2
neighbours = [
    {id="0208", angle=283},
    {id="0215", angle=103},
    {id="0301", angle=90}
]


[[spheres]]
id = "0215"
space = 2
neighbours = [
    {id="0214", angle=283},
    {id="0216", angle=103}
]


[[spheres]]
id = "0216"
space = 2
neighbours = [
    {id="0201", angle=283},
    {id="0202", angle=103}
]


[[spheres]]
id = "0401"
space = 4
neighbours = [
    {id="0303", angle=283},
    {id="0402", angle=283}
]


[[spheres]]
id = "0402"
space = 4
neighbours = [
    {id="0401", angle=283},
    {id="0403", angle=283}
]


[[spheres]]
id = "0403"
space = 4
neighbours = [
    {id="0402", angle=283},
    {id="0405", angle=283}
]


[[spheres]]
id = "0405"
space = 4
neighbours = [
    {id="0403", angle=283},
    {id="0406", angle=283}
]


[[spheres]]
id = "0406"
space = 4
neighbours = [
    {id="0405", angle=283},
    {id="0407", angle=283}
]


[[spheres]]
id = "0407"
space = 4
neighbours = [
    {id="0406", angle=283},
    {id="0408", angle=283}
]


[[spheres]]
id = "0408"
space = 4
neighbours = [
    {id="0407", angle=283},
    {id="0409", angle=283}
]


[[spheres]]
id = "0409"
space = 4
neighbours = [
    {id="0408", angle=283},
    {id="0410", angle=283}
]


[[spheres]]
id = "0410"
space = 4
neighbours = [
    {id="0409", angle=283},
    {id="0411", angle=283},
    {id="0501", angle=283}
]


[[spheres]]
id = "0411"
space = 4
neighbours = [
    {id="0410", angle=283}
]


[[spheres]]
id = "0501"
space = 5
neighbours = [
    {id="0409", angle=283},
    {id="0410", angle=283},
    {id="0502", angle=283},
    {id="0801", angle=283}
]


[[spheres]]
id = "0502"
space = 5
neighbours = [
    {id="0501", angle=283},
    {id="0503", angle=283}
]


[[spheres]]
id = "0503"
space = 5
neighbours = [
    {id="0502", angle=283},
    {id="0504", angle=283}
]


[[spheres]]
id = "0504"
space = 5
neighbours = [
    {id="0503", angle=283},
    {id="0505", angle=283}
]


[[spheres]]
id = "0505"
space = 5
neighbours = [
    {id="0504", angle=283},
    {id="0506", angle=283}
]


[[spheres]]
id = "0506"
space = 5
neighbours = [
    {id="0505", angle=283},
    {id="0507", angle=283}
]


[[spheres]]
id = "0507"
space = 5
neighbours = [
    {id="0506", angle=283},
    {id="0508", angle=283}
]


[[spheres]]
id = "0508"
space = 5
neighbours = [
    {id="0507", angle=283},
    {id="0509", angle=283}
]


[[spheres]]
id = "0509"
space = 5
neighbours = [
    {id="0508", angle=283},
    {id="2101", angle=283}
]





